// Peticiones a Categorias
@api_categorias = http://localhost:5000/categorias

###
GET {{api_categorias}}

###
POST {{api_categorias}}
Content-Type: application/json

{
    "Nombre":"Refrescos"
}
### Consulta de producto por id
GET {{api_categorias}}/7

### Consulta para elminar un producto por su id
DELETE {{api_categorias}}/6

### Consulta para actualizar los productos por id
PUT {{api_categorias}}/7
Content-Type: application/json

{
    "Nombre":"Postres"
}