// Peticiones a productos
//@api_productos = https://antojitosmex.herokuapp.com/productos
@api_productos = http://localhost:5000/productos

### Consulta de Todos los pructos existentes en la tabla
GET {{api_productos}}

### Consulta de insercion de productos
POST {{api_productos}}
Content-Type: application/json

{
    "Nombre":"Refil de refresco",
    "Precio": 20.00,
    "Descripcion":"Vaso rellenable de cualquier refresco de 450ml",
    "Categoria": "Refrescos",
    "Disponibilidad":"1"
}
### Consulta de producto por id
GET {{api_productos}}/1

### Consulta para elminar un producto por su id
DELETE {{api_productos}}/8

### Consulta para actualizar los productos por id
PUT {{api_productos}}/2
Content-Type: application/json

{
    "Nombre":"Tacos de canasta",
    "Precio": 55.00,
    "Descripcion":"Orden de tacos de canasta con cueros y salsas roja y verde",
    "Categoria":"Comidas",
    "Disponibilidad":"1"
}